NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.adviser.mtct.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.adviser.mtct.com-cert.pem
    OrganizationalUnitIdentifier: peer
