NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.hquarter.mtct.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.hquarter.mtct.com-cert.pem
    OrganizationalUnitIdentifier: peer
