NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.invester.mtct.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.invester.mtct.com-cert.pem
    OrganizationalUnitIdentifier: peer
